Fix build problem due to missing header for size_t
I get this error when compiling with clang 3.7.1:

    ./tiny_cnn/config.h:76:9: error: 'size_t' does not name a type
     typedef size_t cnn_size_t;

Including the header for size_t should fix this.